inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
Layout/HashAlignment:
  Exclude:
    - '*.gemspec'
Layout/LineLength:
  AllowedPatterns: ['\A\s*#'] # Ignore comments, there is no way to configure commonmarker for yard to disable non commonmark compliant linebreak injection, so inserting newline breaks the paragraph
Metrics/BlockLength:
  Exclude:
    - 'lib/adassault/cli/*.rb' # it's necessary by gli design
Style/Documentation:
  Exclude:
    # https://github.com/rubocop/rubocop/issues/13014
    # false positive edge case issue
    # already documented in lib/adassault/cli.rb
    - 'lib/adassault/cli/*.rb'
